### ISSUE TITLE
Add brew installation instructions

### ISSUE THREAD

**Issue by sagikazarmark** [yuya-takeyama/helmenv#3]
Would be nice if this tool could be installed as a brew package, just like tfenv

**Comment by Grejeru** [comment]
First of all app needs to be released, so brew formula can be created to release archive file.

**Comment by sagikazarmark** [comment]
Not necessarily, but that would indeed be nice, too.

Here is a formula, that works with the current version:

https://github.com/sagikazarmark/homebrew-thirdparty/blob/master/Formula/helmenv.rb

**Comment by yuya-takeyama** [comment]
@sagikazarmark @Grejeru 
Thanks for your comments.

But I'm no longer maintaining this software.
Please refer this commit:
https://github.com/yuya-takeyama/helmenv/commits/master
